// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async isDbInitialized(): Promise<boolean> {
    return await TAURI_INVOKE('is_db_initialized');
  },
  async initDatabase(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('init_database') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async showMainWindow(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('show_main_window') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Retrieve a manufacturer by its identifier.
   *
   * Parses the provided `manufacturer_id` into a domain `ManufacturerId`,
   * acquires a database connection from the application state, and queries the
   * repository for the matching `Manufacturer`.
   *
   * # Arguments
   *
   * * `state` - Tauri-managed application `AppState` (provides DB pool).
   * * `manufacturer_id` - The manufacturer identifier as a `String`.
   *
   * # Returns
   *
   * Returns `Ok(Some(Manufacturer))` when a matching manufacturer exists,
   * `Ok(None)` when no matching row is found, or `Err(CommandError)` when the
   * ID cannot be parsed or a database error occurs.
   */
  async getManufacturerById(
    manufacturerId: string
  ): Promise<Result<Manufacturer | null, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_manufacturer_by_id', { manufacturerId })
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Retrieve a railway model by id. Returns the model even if it has no rolling stocks.
   */
  async getRailwayModelById(
    railwayModelId: string
  ): Promise<Result<RailwayModel | null, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_railway_model_by_id', { railwayModelId })
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Retrieve multiple railway models by their identifiers.
   */
  async getRailwayModelsByIds(
    railwayModelIds: string[]
  ): Promise<Result<RailwayModel[], CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_railway_models_by_ids', { railwayModelIds })
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Retrieve a railway company by its identifier.
   *
   * Parses the provided `railway_company_id` into a domain `RailwayCompanyId`,
   * acquires a database connection from the application state, and queries the
   * repository for the matching `RailwayCompany`.
   *
   * # Arguments
   *
   * * `state` - Tauri-managed application `AppState` (provides DB pool).
   * * `railway_company_id` - The railway company identifier as a `String`.
   *
   * # Returns
   *
   * Returns `Ok(Some(RailwayCompany))` when a matching company exists,
   * `Ok(None)` when no matching row is found, or `Err(CommandError)` when the
   * ID cannot be parsed or a database error occurs.
   *
   * # Errors
   *
   * Parsing errors for the identifier and database errors are mapped to
   * `CommandError` and returned to the caller.
   */
  async getRailwayCompanyById(
    railwayCompanyId: string
  ): Promise<Result<RailwayCompany | null, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_railway_company_by_id', { railwayCompanyId })
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Create a new railway model with rolling stocks.
   *
   * This command follows the Unit of Work + Use Case pattern:
   * 1. Creates a SqliteUnitOfWork (transaction)
   * 2. Instantiates the CreateRailwayModelUseCase
   * 3. Executes the use case with validated input
   * 4. Commits the transaction on success
   * 5. Returns the created railway model ID
   *
   * # Arguments
   *
   * * `state` - Tauri-managed application `AppState` (provides DB pool).
   * * `input` - The railway model creation input data.
   *
   * # Returns
   *
   * Returns `Ok(String)` with the newly created railway model ID on success,
   * or `Err(CommandError)` if validation, database, or business logic fails.
   */
  async createRailwayModel(input: CreateRailwayModelInput): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('create_railway_model', { input }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Tauri command to retrieve the current collection.
   *
   * This handler constructs the repository and use-case, executes the use-case
   * asynchronously and returns the `Collection` on success. On failure, it
   * converts the error into a `CommandError::Unknown` preserving the error
   * message for logging/debugging.
   *
   * Parameters:
   * - `state`: Tauri-managed application state which provides a database pool.
   *
   * Returns:
   * - `Ok(Collection)` when retrieval succeeds.
   * - `Err(CommandError)` when the use-case returns an error.
   */
  async getCollection(): Promise<Result<Collection, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_collection') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Tauri command to retrieve depot data (alias of `get_collection`).
   */
  async getDepot(): Promise<Result<Collection, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_depot') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async listCollectionItems(
    search: string | null
  ): Promise<Result<CollectionItemLite[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('list_collection_items', { search }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async createCollectionItem(
    input: CreateCollectionItemInput
  ): Promise<Result<CollectionItemLite, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('create_collection_item', { input }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async updateCollectionItem(
    input: UpdateCollectionItemInput
  ): Promise<Result<CollectionItemLite, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('update_collection_item', { input }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async deleteCollectionItem(id: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('delete_collection_item', { id }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getWishlists(): Promise<Result<WishlistPreview[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_wishlists') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getWishlistById(id: string): Promise<Result<Wishlist | null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_wishlist_by_id', { id }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async createWishlist(input: CreateWishlistInput): Promise<Result<WishlistPreview, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('create_wishlist', { input }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async renameWishlist(input: RenameWishlistInput): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('rename_wishlist', { input }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async deleteWishlist(id: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('delete_wishlist', { id }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async setDefaultWishlist(id: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('set_default_wishlist', { id }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async addToWishlist(input: AddToWishlistInput): Promise<Result<WishlistItem, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('add_to_wishlist', { input }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async removeFromWishlist(itemId: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('remove_from_wishlist', { itemId }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async moveItemToList(input: MoveWishlistItemInput): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('move_item_to_list', { input }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Retrieve maintenance cards that are due or overdue.
   */
  async getMaintenanceDashboard(): Promise<Result<MaintenanceCard[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_maintenance_dashboard') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * Add a maintenance record and update the card.
   */
  async addMaintenanceRecord(input: AddMaintenanceInput): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('add_maintenance_record', { input }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getSellers(): Promise<Result<Seller[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_sellers') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getSellerById(id: string): Promise<Result<Seller | null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_seller_by_id', { id }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async createSeller(payload: CreateSellerPayload): Promise<Result<Seller, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('create_seller', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async updateSeller(payload: UpdateSellerPayload): Promise<Result<Seller, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('update_seller', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async deleteSeller(id: string): Promise<Result<bigint, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('delete_seller', { id }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async dashboardSummary(): Promise<Result<DashboardSummary, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('dashboard_summary') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getImagePath(id: string, category: string): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_image_path', { id, category }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getAppVersion(): Promise<string> {
    return await TAURI_INVOKE('get_app_version');
  },
  async getSettings(): Promise<Result<SettingsDto, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_settings') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async updateSettings(payload: UpdateSettingsPayload): Promise<Result<SettingsDto, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('update_settings', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  }
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

/**
 * Input DTO for adding a maintenance record over IPC.
 */
export type AddMaintenanceInput = {
  id: string;
  maintenance_card_id: string;
  date_performed: string;
  maintenance_type: string | null;
  notes: string | null;
};
export type AddToWishlistInput = {
  wishlistId: string;
  railwayModelId: string;
  priority: WishlistPriority | null;
  status: WishlistStatus | null;
  desiredPriceAmount: bigint | null;
  desiredPriceCurrency: string | null;
  notes: string | null;
  addedDate: string | null;
};
/**
 * It represents a physical street address
 */
export type Address = {
  /**
   * the street address
   */
  street_address: string;
  /**
   * the (optional) extended information for the address
   */
  extended_address: string | null;
  /**
   * the city/town
   */
  city: string;
  /**
   * the region code; for example, the state or province.
   */
  region: string | null;
  /**
   * the postal code (ZIP code)
   */
  postal_code: string;
  /**
   * the ISO country code (ISO 3166-1 alpha-3)
   */
  country: string;
};
/**
 * Lifecycle availability status of a railway model.
 *
 * The enum variants represent common product lifecycle states. When
 * serialized via `serde` the variants use SCREAMING_SNAKE_CASE; likewise
 * string parsing via `strum` expects SCREAMING_SNAKE_CASE but is
 * case-insensitive.
 */
export type AvailabilityStatus =
  /**
   * The railway model is just announced and not yet available.
   */
  | 'ANNOUNCED'
  /**
   * The railway model is available for purchase.
   */
  | 'AVAILABLE'
  /**
   * The railway model production / release has been cancelled or delayed
   * (not proceeding as previously announced).
   */
  | 'CANCELLED'
  /**
   * The railway model has been discontinued and is no longer produced.
   */
  | 'DISCONTINUED';
/**
 * The construction type of rolling stock's body shell.
 *
 * This enum describes the material / manufacturing technique used for the outer
 * body shell of a model (for example, a plastic injection-moulded shell vs a
 * metal die-cast shell). It is used in technical specifications to describe
 * the build of the vehicle's exterior.
 */
export type BodyShellType =
  /**
   * Plastic body shell construction (typically injection moulded plastic).
   */
  | 'PLASTIC'
  /**
   * Metal die-cast body shell construction (heavier, metal cast components).
   */
  | 'METAL_DIE_CAST';
/**
 * The enumeration of the railway model categories.
 */
export type Category =
  /**
   * Independent traction units powered by steam, diesel, or electricity
   * used to pull unpowered vehicles.
   */
  | 'LOCOMOTIVES'
  /**
   * Pre-configured groups of permanently or semi-permanently coupled
   * vehicles, such as high-speed trains.
   */
  | 'TRAIN_SETS'
  /**
   * All-in-one entry-level packages typically including a train,
   * track, and a power controller.
   */
  | 'STARTER_SETS'
  /**
   * Vehicles designed for the transport of physical goods,
   * raw materials, or equipment.
   */
  | 'FREIGHT_CARS'
  /**
   * Vehicles designed for the transport of people, typically
   * including seating, lighting, and climate control.
   */
  | 'PASSENGER_CARS'
  /**
   * Self-propelled train sets consisting of multiple carriages
   * using electricity as their motive power.
   */
  | 'ELECTRIC_MULTIPLE_UNITS'
  /**
   * Lightweight, self-propelled vehicles (usually a single unit)
   * designed for passenger service on branch lines.
   */
  | 'RAILCARS';
/**
 * The construction type of a rolling stock's chassis.
 *
 * This enum indicates the material or manufacturing technique used for the
 * chassis (the structural frame and underbody) of a model. It is part of
 * the technical specifications describing the build quality and expected
 * properties of the model's underframe.
 */
export type ChassisType =
  /**
   * Plastic chassis construction (typically injection-moulded plastic).
   */
  | 'PLASTIC'
  /**
   * Metal die-cast chassis construction (heavier, metal cast chassis parts).
   */
  | 'METAL_DIE_CAST';
/**
 * Represents a user-owned collection of items.
 *
 * A `Collection` contains identifying information, a few aggregated summary
 * values and the list of `CollectionItem` entries that make up the
 * collection. It is intentionally lightweight to keep IPC payloads small.
 *
 * Default behaviour:
 * - `Collection::default()` returns an empty collection with a generated id,
 * the name "My Collection", a `CollectionSummary::default()` and no
 * `total_value` (i.e. `None`). This mirrors previous code paths that
 * returned a default when no database row existed.
 */
export type Collection = {
  /**
   * Unique identifier for the collection (typically a UUID stored as a string).
   */
  id: CollectionId;
  /**
   * Display name for this collection.
   */
  name: string;
  /**
   * Precomputed summary counts (e.g. total items, tracked vs untracked).
   */
  summary: CollectionSummary;
  /**
   * Optional total monetary value of the collection. Use `MonetaryAmount`
   * to preserve currency and decimal precision.
   */
  total_value: MonetaryAmount | null;
  /**
   * The list of items contained in this collection.
   */
  items: CollectionItem[];
};
/**
 * Identifier for a collection.
 *
 * This newtype wraps a `String` containing a TRN of the form
 * `trn:collection:1`. Construction from strings is fallible — the string must
 * exactly match the enforced TRN for the single-supported collection.
 */
export type CollectionId = string;
/**
 * A single item within a user's collection.
 *
 * A `CollectionItem` represents a reference to a catalog `RailwayModel` along
 * with ownership-specific data such as the rolling stock instances owned by
 * the collector and purchase information. It is intentionally a lightweight
 * entity that is meaningful only inside the context of its parent
 * `Collection` (the aggregate root).
 */
export type CollectionItem = {
  /**
   * Unique identifier for this collection item (e.g. UUID).
   */
  id: CollectionItemId;
  /**
   * Link to the corresponding catalog `RailwayModel` this item represents.
   *
   * This is a reference to the canonical model in the catalog; use this
   * to look up full catalog details (manufacturer, product codes, etc.).
   */
  railway_model_id: string;
  /**
   * Condition of the item as recorded by the owner (e.g. "mint", "used").
   */
  conditions: string | null;
  /**
   * Free-form notes provided by the owner for this collection item.
   */
  notes: string | null;
  /**
   * The specific rolling stock instances owned that correspond to this model.
   */
  rolling_stocks: OwnedRollingStock[];
  /**
   * Optional purchase information associated with this collection item.
   */
  purchase_info: PurchaseInfo | null;
};
/**
 * Identifier for a single item in a collection.
 *
 * This newtype wraps a `String` containing a TRN of the form
 * `trn:collection-item:{uuid}`. Construction from strings is fallible — the
 * string must start with the TRN prefix and the suffix must be a valid UUID.
 */
export type CollectionItemId = string;
/**
 * Core collection item representation surfaced to the frontend.
 */
export type CollectionItemLite = {
  id: string;
  brand: string;
  catalogNumber: string;
  title: string;
  scale: string;
  powerSystem: string;
  description: string | null;
  tags: string[];
  createdAt: string;
};
/**
 * A statistical summary of a model railway collection.
 *
 * This struct provides a high-level overview of the total quantities
 * of different types of rolling stock within a specific inventory or sub-collection.
 */
export type CollectionSummary = {
  /**
   * The total number of independent traction units (Steam, Diesel, Electric).
   */
  locomotives_count: number;
  /**
   * The total number of individual passenger-carrying vehicles.
   */
  passenger_cars_count: number;
  /**
   * The total number of individual goods-transporting vehicles.
   */
  freight_cars_count: number;
  /**
   * The number of complete train sets (e.g., starter sets or fixed formations).
   *
   * Note: Depending on implementation, the individual cars within these sets
   * may or may not be included in the other specific counts.
   */
  train_sets_count: number;
  /**
   * The number of self-propelled, typically single-unit passenger vehicles.
   */
  railcars_count: number;
  /**
   * The number of self-propelled, multi-unit electric passenger formations.
   */
  electric_multiple_units_count: number;
};
/**
 * Application-level error returned by command handlers in the core infrastructure.
 *
 * This enum provides structured error variants that allow the frontend to react
 * intelligently to different error conditions. Each variant is serializable and
 * includes enough context for appropriate UI rendering.
 */
export type CommandError =
  /**
   * Represents an error coming from the database layer.
   *
   * The inner `String` should contain a concise, non-sensitive description
   * of the underlying database failure.
   */
  | { DatabaseError: string }
  /**
   * Indicates a requested resource was not found.
   *
   * Use this when a query returns no results for a specific ID or criteria.
   * The inner `String` should describe what resource was not found (e.g., "Wishlist not found").
   */
  | { NotFound: string }
  /**
   * Validation error with field-specific messages.
   *
   * The map contains field names as keys and error messages as values.
   * This allows the frontend to display validation errors next to the appropriate form fields.
   * Example: `{"email": "Invalid email format", "age": "Must be at least 18"}`
   */
  | { ValidationError: Partial<{ [key in string]: string }> }
  /**
   * Permission denied for the requested operation.
   *
   * Use this when the user lacks sufficient privileges to perform an action.
   */
  | { PermissionDenied: string }
  /**
   * A catch-all for unexpected errors that don't map to a specific variant.
   *
   * The inner `String` can include a short debug message suitable for
   * logging; avoid placing secrets here.
   */
  | { Unknown: string };
/**
 * The control method for this railway model.
 *
 * The `Control` enum captures whether a model is DCC-ready, has a decoder
 * fitted, has a sound-equipped decoder, or has no DCC support at all.
 *
 * Variants:
 * - `DccReady`: The model is prepared for a DCC decoder (e.g. a standard
 * decoder plug is present) but no decoder is installed.
 * - `DccFitted`: A DCC decoder has been installed.
 * - `DccSound`: A DCC decoder with a sound module is installed.
 * - `NoDcc`: The model does not support DCC (no standard interface present);
 * installation may require model-specific wiring or a hardwired decoder.
 */
export type Control =
  /**
   * The model can be fitted with a dcc decoder.
   */
  | 'DCC_READY'
  /**
   * The model has a dcc decoder installed.
   */
  | 'DCC_FITTED'
  /**
   * The model has a dcc decoder installed with the sound module.
   */
  | 'DCC_SOUND'
  /**
   * The model has no dcc support (like no standard decoder plug)
   */
  | 'NO_DCC';
/**
 * It represents the coupling configuration for a rolling stock.
 */
export type Coupling = {
  /**
   * the rolling stock coupling socket
   */
  socket: CouplingSocket | null;
  /**
   * the rolling stock has a close coupling mechanism
   */
  close_couplers: FeatureFlag | null;
  /**
   * the rolling stock has a digital shunting couplers mechanism
   */
  digital_shunting: FeatureFlag | null;
};
export type CouplingInput = {
  socket: string;
  close_couplers: string | null;
  digital_shunting: string | null;
};
export type CouplingSocket =
  | 'NONE'
  /**
   * Receptacle for Replaceable Coupling Heads in Scales TT and N
   */
  | 'NEM_355'
  /**
   * Coupler Head for Scale N
   */
  | 'NEM_356'
  /**
   * Coupler Head for Scale N
   */
  | 'NEM_357'
  /**
   * Coupler Head for Scale TT
   */
  | 'NEM_359'
  /**
   * Standard Coupling for Scale H0
   */
  | 'NEM_360'
  /**
   * NEM shaft 362 with close coupling mechanism
   */
  | 'NEM_362'
  /**
   * Coupler Head for Scale 0
   */
  | 'NEM_365';
/**
 * Payload for creating a collection item.
 */
export type CreateCollectionItemInput = {
  brand: string;
  catalogNumber: string;
  title: string;
  scale: string;
  powerSystem: string;
  description: string | null;
  tags: string[];
};
/**
 * Input for creating a new railway model (domain-level DTO).
 */
export type CreateRailwayModelInput = {
  manufacturer_id: string;
  product_code: string;
  description: string;
  details: string | null;
  power_method: string;
  scale: string;
  epoch: string;
  category: string;
  delivery_date: string | null;
  availability_status: string | null;
  rolling_stocks: CreateRollingStockInput[];
};
/**
 * Input for creating a rolling stock (tagged union by category).
 */
export type CreateRollingStockInput =
  | {
      category: 'Locomotive';
      railway_company_id: string;
      friendly_name: string;
      series_code: string;
      road_number: string;
      series: string | null;
      depot: string | null;
      livery: string | null;
      locomotive_type: string;
      is_dummy: boolean | null;
      control: string | null;
      dcc_interface: string | null;
      length_over_buffers: LengthOverBuffersInput | null;
      technical_specifications: TechnicalSpecificationsInput | null;
    }
  | {
      category: 'PassengerCar';
      railway_company_id: string;
      friendly_name: string;
      series_code: string;
      road_number: string | null;
      series: string | null;
      depot: string | null;
      livery: string | null;
      passenger_car_type: string;
      service_level: string | null;
      length_over_buffers: LengthOverBuffersInput | null;
      technical_specifications: TechnicalSpecificationsInput | null;
    }
  | {
      category: 'FreightCar';
      railway_company_id: string;
      friendly_name: string;
      series_code: string;
      road_number: string | null;
      series: string | null;
      depot: string | null;
      livery: string | null;
      freight_car_type: string | null;
      length_over_buffers: LengthOverBuffersInput | null;
      technical_specifications: TechnicalSpecificationsInput | null;
    }
  | {
      category: 'Railcar';
      railway_company_id: string;
      friendly_name: string;
      series_code: string;
      road_number: string | null;
      series: string | null;
      depot: string | null;
      livery: string | null;
      control: string | null;
      dcc_interface: string | null;
      length_over_buffers: LengthOverBuffersInput | null;
      technical_specifications: TechnicalSpecificationsInput | null;
    }
  | {
      category: 'ElectricMultipleUnit';
      railway_company_id: string;
      friendly_name: string;
      series_code: string;
      road_number: string | null;
      series: string | null;
      depot: string | null;
      livery: string | null;
      electric_multiple_unit_type: string;
      is_dummy: boolean | null;
      control: string | null;
      dcc_interface: string | null;
      length_over_buffers: LengthOverBuffersInput | null;
      technical_specifications: TechnicalSpecificationsInput | null;
    };
export type CreateSellerPayload = {
  name: string;
  sellerType: SellerType;
  email: string | null;
  phone: string | null;
  websiteUrl: string | null;
  streetAddress: string | null;
  extendedAddress: string | null;
  city: string | null;
  stateRegion: string | null;
  postalCode: string | null;
  countryCode: string | null;
};
export type CreateWishlistInput = { name: string; notes: string | null; isDefault: boolean | null };
/**
 * Currency codes supported by the application.
 *
 * The enum uses a small, explicit set of currencies for now. Use
 * `Currency::from_code` to obtain a `Currency` value from an ISO-style
 * currency code (case-insensitive).
 */
export type Currency =
  /**
   * Euro
   */
  | 'EUR'
  /**
   * United States Dollar
   */
  | 'USD'
  /**
   * Great Britain Pound
   */
  | 'GBP'
  /**
   * Japanese Yen
   */
  | 'JPY';
export type DashboardDepotEntry = {
  id: string;
  manufacturer: string | null;
  productCode: string | null;
  category: string | null;
  scale: string | null;
  railwayCompany: string | null;
  description: string | null;
};
export type DashboardRecentItem = { id: string; title: string; subtitle: string | null };
export type DashboardSummary = {
  totals: DashboardTotals;
  recentItems: DashboardRecentItem[];
  depotItems: DashboardDepotEntry[];
};
export type DashboardTotals = {
  collectionItems: number;
  wishlists: number;
  maintenanceDue: number;
  totalValue: MonetaryAmountSummary | null;
};
/**
 * The NMRA and NEM Connectors for digital control (DCC)
 *
 * # Description
 * The NMRA and NEM adopted standard mechanical and electrical interfaces to connect Multifunction
 * Decoders to a locomotive's electrical system. These plugs and sockets make it simpler to install
 * a decoder into a suitably equipped locomotive.
 *
 * In many cases a blanking plug must be removed before installing the decoder. If a locomotive
 * is not DCC-Ready it will lack an interface and must use a Hardwired Decoder or a drop-in
 * replacement DCC control board (if available) for that specific model.
 */
export type DccInterface =
  /**
   * 6 Pin standard mechanical and electrical interfaces (NMRA Small)
   */
  | 'NEM_651'
  /**
   * 8 Pin standard mechanical and electrical interfaces (NMRA Medium)
   */
  | 'NEM_652'
  /**
   * 4 Pin standard mechanical and electrical interfaces (NMRA Large)
   */
  | 'NEM_654'
  /**
   * The PluX8 connector consists of two rows of 4 pins.
   */
  | 'PLUX_8'
  | 'PLUX_12'
  /**
   * The PluX16 connector consists of two rows of 8 pins.
   */
  | 'PLUX_16'
  /**
   * The PluX22 connector consists of two rows of 11 pins.
   */
  | 'PLUX_22'
  /**
   * standard connector for extremely tight applications, such as TT and N scale locomotives (NEM 662)
   */
  | 'NEXT_18'
  | 'NEXT_18_S'
  /**
   * 21MTC Connector interface is a standard adopted by both the NMRA and NEM (NEM 660).
   * Its name comes from 21 pin Marklin/Trix Connector, developed by Marklin and ESU.
   */
  | 'MTC_21';
/**
 * Strongly-typed identifier for a decoder (master record).
 *
 * This newtype is `#[repr(transparent)]` and serializes as a plain string.
 * URNs are of the form `trn:decoder:{manufacturer}:{product_code}`.
 */
export type DecoderId = string;
/**
 * Represents the expected delivery timeframe for a railway model.
 *
 * This enum allows for varying levels of precision depending on how
 * much information the manufacturer has provided about the release schedule.
 */
export type DeliveryDate =
  /**
   * Delivery is expected within a specific calendar year.
   */
  | { Year: number }
  /**
   * Delivery is expected within a specific month of a year.
   */
  | {
      YearMonth: {
        /**
         * The calendar year (e.g., 2024).
         */
        year: number;
        /**
         * The month of the year (1 for January, 12 for December).
         */
        month: number;
      };
    }
  /**
   * Delivery is expected within a specific fiscal or calendar quarter.
   */
  | {
      YearQuarter: {
        /**
         * The calendar year (e.g., 2024).
         */
        year: number;
        /**
         * The specific quarter of the year.
         */
        quarter: Quarter;
      };
    };
/**
 * Represents the installation of a decoder into a locomotive (owned rolling stock).
 */
export type DigitalSetup = {
  /**
   * The physical interface present on the locomotive (socket/plug type).
   */
  interface: DccInterface;
  /**
   * The DCC address assigned to the decoder.
   */
  dcc_address: number;
  /**
   * The installed decoder id (URN) referencing the `decoders` master table.
   */
  installed_decoder_id: DecoderId;
};
/**
 * The cars that form a complete EMU set can usually be separated by function into four types:
 * power car, motor car, driving car, and trailer car.
 *
 * Each car can have more than one function, such as a motor-driving car or power-driving car.
 */
export type ElectricMultipleUnitType =
  /**
   * Driving cars are similar to a cab car, containing a driver's cab for controlling the train.
   * An EMU will usually have two driving cars at its outer ends.
   */
  | 'DRIVING_CAR'
  /**
   * High-speed rail is a type of rail system that runs significantly faster than traditional
   * rail, using an integrated system of specialised rolling stock and dedicated tracks.
   */
  | 'HIGH_SPEED_TRAIN'
  /**
   * Motor cars carry the traction motors to move the train, and are often combined with the
   * power car to avoid high-voltage inter-car connections.
   */
  | 'MOTOR_CAR'
  /**
   * A power car carries the necessary equipment to draw power from the electrified
   * infrastructure, such as pickup shoes for third rail systems and pantographs for
   * overhead systems, and transformers.
   */
  | 'POWER_CAR'
  /**
   * Trailer cars are any cars (sometimes semi-permanently coupled) that carry little or no
   * traction or power related equipment, and are similar to passenger cars in a
   * locomotive-hauled train.
   */
  | 'TRAILER_CAR'
  /**
   * A trainset is working as whole unit
   */
  | 'TRAIN_SET';
/**
 * Backwards-compatible wrapper used across the codebase and DB rows.
 *
 * This preserves the original `Epoch(pub String)` API while providing
 * conversions to the structured `EpochKind` for validation and richer handling.
 */
export type Epoch = string;
/**
 * Represents the availability or relevance of a specific model feature.
 *
 * This is often used for technical specifications where a feature might
 * exist, be intentionally absent, or simply not be relevant to that
 * specific class of locomotive or rolling stock.
 */
export type FeatureFlag =
  /**
   * The feature is present and functional on the model.
   */
  | 'YES'
  /**
   * The feature is not present on the model, though it might be
   * expected or available on similar models.
   */
  | 'NO'
  /**
   * The feature is not relevant for this type of equipment.
   *
   * For example, a "Pantograph Type" flag would be `NotApplicable`
   * for a Steam Locomotive.
   */
  | 'NOT_APPLICABLE';
/**
 * Represents the various types of freight rolling stock used in rail transport.
 *
 * These classifications are based on the physical design and the specific
 * cargo requirements, such as climate control, weather protection, or
 * specialized loading mechanisms.
 */
export type FreightCarType =
  /**
   * Specialized wagons for transporting motor vehicles, often multi-deck.
   */
  | 'AUTO_TRANSPORT_CARS'
  /**
   * A wagon equipped with a handbrake or a cabin for a brakeman,
   * historically used to assist in braking the train.
   */
  | 'BRAKE_WAGON'
  /**
   * Wagons designed specifically for carrying cargo that
   * requires full enclosure and protection from the elements.
   */
  | 'CLOSED_CARGO_VEHICLE'
  /**
   * Flat or skeleton-framed wagons designed specifically to carry
   * standardized shipping containers (ISO containers).
   */
  | 'CONTAINER_CARS'
  /**
   * Fully enclosed wagons used for goods that must be protected
   * from weather and theft.
   */
  | 'COVERED_FREIGHT_CARS'
  /**
   * Wagons with a lowered center section designed to carry tall
   * loads like intermodal trailers or containers within height clearances.
   */
  | 'DEEP_WELL_FLAT_CARS'
  /**
   * Open-top wagons with a mechanism to tilt the body to unload
   * bulk materials like sand or gravel.
   */
  | 'DUMP_CARS'
  /**
   * Open-topped rail vehicles used for transporting loose bulk
   * materials such as coal, ore, or scrap metal.
   */
  | 'GONDOLA'
  /**
   * Heavy-duty flat wagons designed for extremely heavy or
   * oversized loads, often featuring many axles.
   */
  | 'HEAVY_GOODS_WAGONS'
  /**
   * Wagons with a roof that is hinged on one side, allowing
   * for top-loading of weather-sensitive bulk goods.
   */
  | 'HINGED_COVER_WAGONS'
  /**
   * Wagons with a floor that slopes toward one or more discharge
   * doors, used for the rapid unloading of bulk materials.
   */
  | 'HOPPER_WAGON'
  /**
   * Insulated wagons equipped with cooling systems for
   * transporting perishable goods.
   */
  | 'REFRIGERATOR_CARS'
  /**
   * Specialized wagons for transporting pressurized or
   * non-pressurized powders and granulated materials in silos.
   */
  | 'SILO_CONTAINER_CARS'
  /**
   * Wagons with a flexible tarpaulin cover that slides open
   * for easy side-loading of palletized goods.
   */
  | 'SLIDE_TARPAULIN_WAGON'
  /**
   * Boxcars with large sliding doors that make up the entire
   * side of the wagon, allowing for forklift access.
   */
  | 'SLIDING_WALL_BOXCARS'
  /**
   * Wagons designed for niche cargo that does not fit
   * into standard classifications.
   */
  | 'SPECIAL_TRANSPORT'
  /**
   * Flat wagons equipped with vertical posts (stakes) along
   * the sides to secure long loads like timber or pipes.
   */
  | 'STAKE_WAGONS'
  /**
   * Wagons with a roof that swings to the side to provide
   * a wide opening for top-loading bulk cargo.
   */
  | 'SWING_ROOF_WAGON'
  /**
   * Enclosed pressurized or non-pressurized vessels for
   * transporting liquids, gases, or chemicals.
   */
  | 'TANK_CARS'
  /**
   * Wagons with several overlapping "hoods" that slide
   * over each other, used for protecting steel coils or heavy machinery.
   */
  | 'TELESCOPE_HOOD_WAGONS';
/**
 * A physical length value paired with its measure unit.
 *
 * The `Length` enum is the canonical representation for lengths in the
 * domain. Each variant stores a `Decimal` quantity for a specific unit.
 *
 * Invariants:
 * - Quantities must be non-negative. Use `Length::try_new` to validate
 * input without panicking.
 * - Equality and ordering compare values after converting to the left-hand
 * side's unit (so comparisons are unit-agnostic but deterministic).
 */
export type Length =
  /**
   * A length expressed in inches.
   */
  | { Inches: string }
  /**
   * A length expressed in kilometers.
   */
  | { Kilometers: string }
  /**
   * A length expressed in meters.
   */
  | { Meters: string }
  /**
   * A length expressed in miles.
   */
  | { Miles: string }
  /**
   * A length expressed in millimeters.
   */
  | { Millimeters: string };
/**
 * The rail vehicle measurement method expressed as the length over buffers
 *
 * `LengthOverBuffers` holds an optional length in both inches and
 * millimeters. When both values are provided they must represent the same
 * physical measure (the constructor will validate that). Values must be
 * positive. The type implements `Copy`/`Clone` and (de)serializes with
 * serde using the helpers in `crate::core::domain::length::serde`.
 */
export type LengthOverBuffers = {
  /**
   * the overall length in inches
   */
  inches: Length | null;
  /**
   * the overall length in millimeters
   */
  millimeters: Length | null;
};
export type LengthOverBuffersInput = { millimeters: number | null; inches: number | null };
/**
 * Specifies the primary motive power source for a locomotive.
 *
 * This classification determines the operational requirements, such as
 * fueling infrastructure or overhead electrification.
 */
export type LocomotiveType =
  /**
   * Locomotives powered by an external combustion engine, typically
   * using a boiler to produce steam from coal, wood, or oil.
   */
  | 'STEAM_LOCOMOTIVE'
  /**
   * Locomotives powered by an internal combustion engine, usually
   * driving an electric generator or a hydraulic transmission.
   */
  | 'DIESEL_LOCOMOTIVE'
  /**
   * Locomotives that draw power from external sources, such as
   * overhead catenary wires or a third rail.
   */
  | 'ELECTRIC_LOCOMOTIVE';
/**
 * Domain model representing a maintenance card for owned rolling stock.
 *
 * This struct contains parsed, strongly-typed fields suitable for use in
 * application logic and for returning to the frontend via Specta.
 */
export type MaintenanceCard = {
  /**
   * Unique identifier for the maintenance card.
   */
  id: string;
  /**
   * FK referencing the owned rolling stock.
   */
  owned_rolling_stock_id: string;
  /**
   * The date the last maintenance was performed, if any.
   */
  last_maintenance_date: string | null;
  /**
   * The scheduled next maintenance date, if any.
   */
  next_maintenance_date: string | null;
  /**
   * Created timestamp parsed from the database (if present).
   */
  created_at: string | null;
  /**
   * Updated timestamp parsed from the database (if present).
   */
  updated_at: string | null;
};
/**
 * A manufacturer (maker of railway models).
 *
 * Fields reflect the `manufacturers` table in the database. Optional fields
 * correspond to nullable DB columns.
 */
export type Manufacturer = {
  /**
   * Unique identifier for the manufacturer.
   */
  id: ManufacturerId;
  /**
   * The common name of the manufacturer (not null).
   */
  name: string;
  /**
   * The legally registered company name (nullable).
   */
  registered_company_name: string | null;
  /**
   * The ISO 3166-1 alpha-2 country code where the company is registered
   * (nullable). Example: `"IT"` for Italy.
   */
  country_code: string | null;
  /**
   * The lifecycle status of the manufacturer. Defaults to `Active`.
   */
  status: ManufacturerStatus;
  /**
   * Optional website URL for the manufacturer.
   */
  website_url: string | null;
};
/**
 * Strongly-typed identifier for a manufacturer in the catalog domain.
 *
 * `ManufacturerId` wraps a `String` and enforces that values constructed via
 * the fallible `TryFrom` implementations are TRNs of the form
 * `trn:manufacturer:{slug}` where `{slug}` is a lowercase ASCII slug made of
 * letters, digits and hyphens (no leading/trailing hyphens, no uppercase).
 *
 * The type serializes and deserializes as a plain string (`serde(transparent)`)
 * and implementing this invariant at construction time avoids accidental use
 * of invalid identifiers across the codebase.
 */
export type ManufacturerId = string;
/**
 * Status of a manufacturer lifecycle.
 *
 * Serialized as SCREAMING_SNAKE_CASE; parsing is case-insensitive.
 */
export type ManufacturerStatus = 'ACTIVE' | 'MERGED' | 'OUT_OF_BUSINESS';
export type MeasureUnit = 'Millimeters' | 'Inches' | 'Meters' | 'Miles' | 'Kilometers';
/**
 * A monetary amount in the smallest currency unit together with its currency.
 *
 * `MonetaryAmount` stores the raw integer amount (e.g. cents) in `amount` and
 * the `currency` that the amount is denominated in. Prefer using the provided
 * constructors rather than populating fields directly.
 *
 * # Examples
 *
 * Basic construction and display:
 *
 * ```rust
 * # use rusty_shed_lib::core::domain::{Currency, MonetaryAmount};
 * let m = MonetaryAmount::new(1050, Currency::EUR);
 * assert_eq!(m.to_string(), "10.50 €");
 * ```
 *
 * Constructing from DB parts (nullable currency):
 *
 * ```rust
 * # use rusty_shed_lib::core::domain::{Currency, MonetaryAmount};
 * let m = MonetaryAmount::from_db(1234, Some("USD")).unwrap();
 * assert_eq!(m.unwrap().currency, Currency::USD);
 * let none = MonetaryAmount::from_db(0, None).unwrap();
 * assert!(none.is_none());
 * ```
 */
export type MonetaryAmount = {
  /**
   * Amount stored in the smallest unit (e.g. cents for EUR/USD/GBP).
   */
  amount: bigint;
  /**
   * Currency of the amount.
   */
  currency: Currency;
};
export type MonetaryAmountSummary = { amount: bigint; currency: string };
export type MoveWishlistItemInput = { itemId: string; destinationWishlistId: string };
/**
 * A lightweight view of rolling stock that references catalog model data.
 *
 * This struct intentionally contains only the minimal information needed by
 * the collecting domain to reference a catalog `RollingStock` and basic
 * provenance. Detailed model information lives in the catalog domain and
 * should not be duplicated here. Fields like railway and epoch are no longer
 * stored on the owned_rolling_stocks table and should be obtained from the
 * catalog when needed.
 */
export type OwnedRollingStock = {
  /**
   * Unique identifier for this owned rolling stock record (e.g. UUID in the DB).
   */
  id: OwnedRollingStockId;
  /**
   * Identifier of the related rolling stock in the catalog (or the owned rolling stock id when catalog id is not available).
   */
  rolling_stock_id: string;
  /**
   * Free-form notes associated with this owned instance.
   * Use this for short owner notes or a brief textual label.
   */
  notes: string;
  /**
   * Optional digital setup information if a decoder is installed.
   */
  digital: DigitalSetup | null;
};
/**
 * Strongly-typed identifier for an `OwnedRollingStock`.
 *
 * A small strongly-typed newtype for owned rolling stock identifiers used by the
 * collecting domain. These identifiers are represented as TRNs (token resource
 * names) and have the form `trn:owned-rolling-stock:{uuid}` where the suffix is
 * a standard UUID (v4) string. The type is serde-transparent so it serializes
 * as a plain string in JSON and database mappings.
 *
 * The inner string is private; construction should use `TryFrom<&str>` to
 * validate the TRN format or `From<Uuid>` / `Default` to generate a fresh id.
 * The type derives `Serialize`/`Deserialize` and is `#[serde(transparent)]` so
 * it appears as a simple string in serialized forms.
 */
export type OwnedRollingStockId = string;
/**
 * The types for passenger car rolling stocks
 */
export type PassengerCarType =
  /**
   * A car usually placed between the locomotive and the rest of the train,
   * featuring a wide-open interior for carrying checked baggage.
   */
  | 'BAGGAGE_CAR'
  /**
   * A car providing limited food service (snacks/drinks) and a counter,
   * smaller in scale than a full Dining Car.
   */
  | 'BUFFET_CAR'
  /**
   * A hybrid car containing separate sections for both passengers and
   * freight or baggage.
   */
  | 'COMBINE_CAR'
  /**
   * A coach featuring a side corridor connecting individual private
   * compartments, each with face-to-face seating rows.
   */
  | 'COMPARTMENT_COACH'
  /**
   * A car dedicated to full-service meal preparation and seating for passengers.
   */
  | 'DINING_CAR'
  /**
   * A car with two levels of passenger seating to increase capacity
   * without increasing train length.
   */
  | 'DOUBLE_DECKER'
  /**
   * A car with a glass-roofed section raised above the normal roofline,
   * allowing 360-degree views of the scenery.
   */
  | 'DOME_CAR'
  /**
   * A control car equipped with a driver's cab, allowing the locomotive
   * to be operated from the opposite end in a push-pull configuration.
   */
  | 'DRIVING_TRAILER'
  /**
   * A car featuring a bar and informal public seating, often used
   * as a social space.
   */
  | 'LOUNGE'
  /**
   * The final car of a train, often featuring large windows or an open
   * rear platform for scenic viewing.
   */
  | 'OBSERVATION'
  /**
   * A coach with a central aisle and rows of seats similar to an
   * airliner's cabin layout.
   */
  | 'OPEN_COACH'
  /**
   * A specialized car used for sorting mail while in transit to
   * expedite delivery.
   */
  | 'RAILWAY_POST_OFFICE'
  /**
   * A car with berths or private rooms for overnight travel.
   * Also known as a "Sleeper" or "Pullman car."
   */
  | 'SLEEPING_CAR'
  /**
   * A "couchette" or "Sleeperette" car, providing reclining seats or
   * basic fold-down bunks for a more economical overnight option.
   */
  | 'SLEEPERETTE';
/**
 * It represents the period of activity for a railway company
 */
export type PeriodOfActivity = {
  /**
   * the date when the railway started its operation
   */
  operating_since: string | null;
  /**
   * the date when the railway ended its operation, if not active anymore
   */
  operating_until: string | null;
  /**
   * the railway status
   */
  status: RailwayStatus;
};
/**
 * Power method used by rolling stocks.
 *
 * This enum represents how a model locomotive obtains electrical power.
 * The `Display` implementation returns a human-friendly name for each variant.
 */
export type PowerMethod =
  /**
   * Alternating current (AC) power collection.
   */
  | 'AC'
  /**
   * Direct current (DC) power collection.
   */
  | 'DC'
  /**
   * Trix Express three-rail power pickup system.
   */
  | 'TRIX_EXPRESS';
/**
 * Details for a pre-order entry.
 *
 * Preorders record at least the deposit paid and the total price expected
 * for the item. Both monetary amounts must use the same currency; use the
 * `validate_currencies_match` helper to assert that condition.
 */
export type PreOrderInfo = {
  /**
   * Unique identifier for this preorder record.
   */
  id: PurchaseInfoId;
  /**
   * Date when the preorder was placed (ISO `YYYY-MM-DD`).
   */
  order_date: string;
  /**
   * Amount paid as deposit (in smallest unit + currency).
   */
  deposit: MonetaryAmount;
  /**
   * Total price for the pre-ordered item (in smallest unit + currency).
   */
  total_price: MonetaryAmount;
  /**
   * Optional seller identifier or shop name.
   */
  seller: string | null;
  /**
   * Optional expected delivery date (ETA) for the preorder.
   */
  expected_date: string | null;
};
/**
 * A product identifier (manufacturer model/code) used to uniquely identify
 * a rolling stock model or catalogue item.
 *
 * This is a thin newtype wrapper around `String` to provide domain-level
 * type-safety and to allow attaching trait impls specific to product codes.
 *
 * It derives `Serialize`/`Deserialize` for easy (de)serialization with Serde.
 *
 * Requirements
 * - The product code MUST be a non-empty, non-blank string. Constructions via
 * `TryFrom<&str>` / `TryFrom<String>` will return an error if the input is
 * empty or contains only whitespace.
 */
export type ProductCode = string;
/**
 * Purchase information associated with a `CollectionItem`.
 *
 * A collection item may have acquisition-related metadata that describes how
 * the user obtained (or intends to obtain) the item. This enum models the
 * three supported acquisition states:
 *
 * - `Purchased`: the item was purchased and its value is counted in the
 * collection total (unless explicitly excluded elsewhere).
 * - `Sold`: the item was sold; we keep a record of the original purchase
 * and the sale, but the item is excluded from the collection's monetary
 * total value.
 * - `PreOrdered`: the item is pre-ordered from a seller; the collector may
 * have paid a deposit and the full total price is known as well.
 */
export type PurchaseInfo =
  /**
   * A standard purchase record.
   */
  | { kind: 'purchased'; data: PurchasedInfo }
  /**
   * A sold item record that preserves original purchase data and the
   * subsequent sale information.
   */
  | { kind: 'sold'; data: SoldInfo }
  /**
   * A preorder record with deposit and total price information.
   */
  | { kind: 'preordered'; data: PreOrderInfo };
/**
 * Strongly-typed identifier for PurchaseInfo records.
 *
 * The inner string is private. Use `TryFrom<&str>` to validate TRN inputs or
 * `From<Uuid>` / `Default` to generate new ids. The type derefs to `str` for
 * ergonomic access to the underlying string.
 */
export type PurchaseInfoId = string;
/**
 * Details for a purchased item.
 *
 * This struct holds the canonical purchase identifier and optional price
 * information. `price` is optional to support legacy records where the
 * monetary amount or currency was not stored.
 */
export type PurchasedInfo = {
  /**
   * Unique identifier for this purchase record (for example a UUID).
   */
  id: PurchaseInfoId;
  /**
   * Date when the item was purchased (ISO `YYYY-MM-DD`).
   */
  purchase_date: string;
  /**
   * The price paid when purchasing the item, if known.
   *
   * Represented as a domain `MonetaryAmount` (amount in smallest unit + currency).
   */
  price: MonetaryAmount | null;
  /**
   * Optional seller identifier or human-friendly name.
   */
  seller: string | null;
};
/**
 * Represents one of the four three-month segments of a calendar year.
 *
 * These quarters follow the standard calendar year, beginning in January.
 */
export type Quarter =
  /**
   * The first quarter: January, February, and March.
   */
  | 'Q1'
  /**
   * The second quarter: April, May, and June.
   */
  | 'Q2'
  /**
   * The third quarter: July, August, and September.
   */
  | 'Q3'
  /**
   * The fourth quarter: October, November, and December.
   */
  | 'Q4';
/**
 * Domain types for handling minimum drivable radii.
 *
 * A `Radius` wraps a `Length` expressed in millimeters and enforces
 * that the value is non-negative.
 */
export type Radius = Length;
/**
 * The types for railcar rolling stocks
 *
 * A railcar is a self-propelled railway vehicle designed to transport passengers.
 * The term _"railcar"_ is usually used in reference to a train consisting of a single coach
 * (carriage, car), with a driver's cab at one or both ends.
 *
 * In its simplest form, a "railcar" may also be little more than a motorized railway handcar
 * or draisine.
 */
export type RailcarType =
  /**
   * A self-propelled passenger vehicles also capable of hauling a train.
   */
  | 'POWER_CAR'
  /**
   * Trailer cars are any cars (sometimes semi-permanently coupled) that carry little or no
   * traction or power related equipment, and are similar to passenger cars in a
   * locomotive-hauled train.
   */
  | 'TRAILER_CAR';
/**
 * A railway company (operator or owner).
 *
 * This struct models a real-world railway company. Some fields are optional
 * because the corresponding database columns may be nullable.
 */
export type RailwayCompany = {
  /**
   * Unique identifier for the railway company.
   */
  id: RailwayCompanyId;
  /**
   * The common name of the railway company (not null).
   */
  name: string;
  /**
   * The legally registered company name (nullable).
   */
  registered_company_name: string | null;
  /**
   * The ISO 3166-1 alpha-2 country code where the company is registered
   * (nullable). Example: `"IT"` for Italy.
   */
  country_code: string | null;
  /**
   * The period of activity of the railway company (nullable).
   */
  period_of_activity: PeriodOfActivity | null;
};
/**
 * Strongly-typed identifier for a railway in the catalog domain.
 *
 * `RailwayId` wraps a string value and provides a distinct type instead of
 * using plain strings everywhere. This improves type safety and makes intent
 * explicit in function signatures and data structures.
 *
 * The inner string is kept private to allow the crate to enforce invariants
 * or to provide controlled constructors/parsers elsewhere. `RailwayId` also
 * derives Serde traits so it serializes/deserializes as a plain string.
 *
 * Requirements
 * - The railway id MUST be a non-empty, non-blank string. Constructions via
 * `TryFrom<&str>` / `TryFrom<String>` will return an error if the input is
 * empty or contains only whitespace.
 */
export type RailwayCompanyId = string;
/**
 * A `RailwayModel` represents a manufactured model product in the catalog.
 *
 * It contains metadata about the product (manufacturer, product code,
 * scale, epoch, etc.) and a list of `RollingStock` instances that correspond
 * to specific owned or catalogued items of this model.
 */
export type RailwayModel = {
  /**
   * Unique identifier for the railway model.
   */
  id: RailwayModelId;
  /**
   * The manufacturer of the model (e.g. Bachmann, Märklin).
   */
  manufacturer: string;
  /**
   * Manufacturer-assigned product code.
   */
  product_code: ProductCode;
  /**
   * Human-readable description of the model.
   */
  description: string;
  /**
   * Additional details about the model (e.g. special features, variations).
   */
  details: string | null;
  /**
   * The power method used by this model (e.g. Diesel, Electric, None for non-powered models).
   */
  power_method: PowerMethod;
  /**
   * The scale of the model (e.g. HO, N).
   */
  scale: Scale;
  /**
   * The historical epoch the model belongs to.
   */
  epoch: Epoch;
  /**
   * Classification category for the model (e.g. locomotive, freight car).
   */
  category: Category;
  /**
   * Delivery or release date information for the product.
   */
  delivery_date: DeliveryDate | null;
  /**
   * the availability status
   */
  availability_status: AvailabilityStatus | null;
  /**
   * Rolling stock instances (specific vehicles) that correspond to this model.
   */
  rolling_stocks: RollingStock[];
};
/**
 * A strongly-typed identifier for a railway model.
 *
 * This newtype wraps a `String` so that code dealing with railway model
 * identifiers can use a distinct type instead of raw `String`s. It derives
 * `Serialize` and `Deserialize` so it can be used directly with `serde`.
 *
 * Requirements
 * - The railway model id MUST be a non-empty, non-blank string. Constructions
 * via `TryFrom<&str>` / `TryFrom<String>` will return an error if the input
 * is empty or contains only whitespace.
 */
export type RailwayModelId = string;
export type RailwayStatus = 'ACTIVE' | 'INACTIVE' | 'MERGED';
export type RenameWishlistInput = { id: string; name: string };
export type RollingStock =
  /**
   * an electric multiple unit rolling stock
   */
  | {
      category: 'ElectricMultipleUnit';
      data: {
        /**
         * the unique identifier for this rolling stock
         */
        id: RollingStockId;
        /**
         * the railway for this rolling stock
         */
        railway: RollingStockRailway;
        /**
         * the livery description
         */
        livery: string | null;
        /**
         * the overall length
         */
        length_over_buffer: LengthOverBuffers | null;
        /**
         * the technical specifications
         */
        technical_specifications: TechnicalSpecifications | null;
        /**
         * the electric multiple unit friendly name
         */
        friendly_name: string;
        /**
         * the series code (eg. a short code identifying the series)
         */
        series_code: string | null;
        /**
         * the identification marking for this electric multiple unit
         */
        road_number: string | null;
        /**
         * the prototype series information
         */
        series: string | null;
        /**
         * the depot name
         */
        depot: string | null;
        /**
         * the electric multiple unit type
         */
        electric_multiple_unit_type: ElectricMultipleUnitType;
        /**
         * the dcc interface
         */
        dcc_interface: DccInterface | null;
        /**
         * the control
         */
        control: Control | null;
        /**
         * indicate whether the rolling stock has a motor or not
         */
        is_dummy: boolean;
      };
    }
  /**
   * a freight car rolling stock
   */
  | {
      category: 'FreightCar';
      data: {
        /**
         * the unique identifier for this rolling stock
         */
        id: RollingStockId;
        /**
         * the railway for this rolling stock
         */
        railway: RollingStockRailway;
        /**
         * the livery description
         */
        livery: string | null;
        /**
         * the overall length
         */
        length_over_buffer: LengthOverBuffers | null;
        /**
         * the technical specifications
         */
        technical_specifications: TechnicalSpecifications | null;
        /**
         * the freight car friendly name
         */
        friendly_name: string;
        /**
         * the series code
         */
        series_code: string | null;
        /**
         * the identification marking for this freight car
         */
        road_number: string | null;
        /**
         * the freight car type
         */
        freight_car_type: FreightCarType | null;
      };
    }
  /**
   * a locomotive rolling stock
   */
  | {
      category: 'Locomotive';
      data: {
        /**
         * the unique identifier for this rolling stock
         */
        id: RollingStockId;
        /**
         * the railway for this rolling stock
         */
        railway: RollingStockRailway;
        /**
         * the livery description
         */
        livery: string | null;
        /**
         * the overall length
         */
        length_over_buffer: LengthOverBuffers | null;
        /**
         * the technical specification
         */
        technical_specifications: TechnicalSpecifications | null;
        /**
         * the locomotive friendly name
         */
        friendly_name: string;
        /**
         * the series code
         */
        series_code: string | null;
        /**
         * the identification marking for this locomotive
         */
        road_number: string;
        /**
         * the prototype series information
         */
        series: string | null;
        /**
         * the depot name
         */
        depot: string | null;
        /**
         * the locomotive type
         */
        locomotive_type: LocomotiveType;
        /**
         * the dcc interface
         */
        dcc_interface: DccInterface | null;
        /**
         * the control
         */
        control: Control | null;
        /**
         * indicate whether the rolling stock has a motor or not
         */
        is_dummy: boolean;
      };
    }
  /**
   * a passenger car rolling stock
   */
  | {
      category: 'PassengerCar';
      data: {
        /**
         * the unique identifier for this rolling stock
         */
        id: RollingStockId;
        /**
         * the railway for this rolling stock
         */
        railway: RollingStockRailway;
        /**
         * the livery description
         */
        livery: string | null;
        /**
         * the overall length
         */
        length_over_buffer: LengthOverBuffers | null;
        /**
         * the technical specifications
         */
        technical_specifications: TechnicalSpecifications | null;
        /**
         * the passenger car friendly name
         */
        friendly_name: string;
        /**
         * the series code
         */
        series_code: string | null;
        /**
         * the identification marking for this passenger car
         */
        road_number: string | null;
        /**
         * the prototype series information
         */
        series: string | null;
        /**
         * the passenger car type
         */
        passenger_car_type: PassengerCarType | null;
        /**
         * the travel class for this passenger car. Passenger cars can have multiple service
         * levels (ie, '1st/2nd')
         */
        service_level: ServiceLevel | null;
      };
    }
  /**
   * a railcar rolling stock
   */
  | {
      category: 'Railcar';
      data: {
        /**
         * the unique identifier for this rolling stock
         */
        id: RollingStockId;
        /**
         * the railway for this rolling stock
         */
        railway: RollingStockRailway;
        /**
         * the livery description
         */
        livery: string | null;
        /**
         * the overall length
         */
        length_over_buffer: LengthOverBuffers | null;
        /**
         * the technical specifications
         */
        technical_specifications: TechnicalSpecifications | null;
        /**
         * the railcar friendly name
         */
        friendly_name: string;
        /**
         * the series code
         */
        series_code: string | null;
        /**
         * the identification marking for this railcar
         */
        road_number: string | null;
        /**
         * the railcar series
         */
        series: string | null;
        /**
         * the depot name
         */
        depot: string | null;
        /**
         * the railcar type
         */
        railcar_type: RailcarType;
        /**
         * the dcc interface
         */
        dcc_interface: DccInterface | null;
        /**
         * the control
         */
        control: Control | null;
        /**
         * indicate whether the rolling stock has a motor or not
         */
        is_dummy: boolean;
      };
    };
/**
 * A unique identifier for a rolling stock represented as a TRN string.
 */
export type RollingStockId = string;
/**
 * A railway association for a rolling stock item.
 *
 * `RollingStockRailway` ties a rolling stock to a specific railway by
 * containing the railway's unique identifier and the display name used in
 * user interfaces and listings. This is a lightweight DTO-like value used in
 * domains where the rolling stock's owning or related railway must be shown
 * or serialized.
 */
export type RollingStockRailway = {
  /**
   * the railway unique identifier
   */
  railway_id: RailwayCompanyId;
  /**
   * the railway display name
   */
  display: string;
};
/**
 * Model railway scales supported by the application.
 *
 * Each variant corresponds to a commonly used hobbyist scale name (for example
 * `H0` or `00`). Use `Scale::ratio()` to obtain the numeric ratio that follows
 * the `1:` notation (e.g. `Scale::H0` -> `1:87`). The `Display` implementation
 * produces a human-friendly string such as `H0 (1:87)`.
 */
export type Scale =
  /**
   * H0 scale (1:87)
   */
  | 'H0'
  /**
   * H0 narrow/metric (1:87)
   */
  | 'H0m'
  /**
   * H0e (1:87)
   */
  | 'H0e'
  /**
   * N scale (1:160)
   */
  | 'N'
  /**
   * TT scale (1:120)
   */
  | 'TT'
  /**
   * Z scale (1:220)
   */
  | 'Z'
  /**
   * G scale (garden) (1:22.5)
   */
  | 'G'
  /**
   * 1 scale (1:32)
   */
  | 'Scale1'
  /**
   * 0 scale (1:43.5)
   */
  | 'Scale0'
  /**
   * 00 (double-zero) scale (1:76.2)
   */
  | 'Scale00';
/**
 * Represents a seller (a shop, private seller or distributor) in the system.
 *
 * This domain-level struct is used by application use-cases and persisted via
 * the sellers repository. Timestamps are represented using `chrono::DateTime<Utc>`.
 */
export type Seller = {
  /**
   * Strongly-typed seller identifier (format: `trn:seller:{slug}`).
   */
  id: SellerId;
  /**
   * Human-readable seller name.
   */
  name: string;
  /**
   * The category/type of the seller (Shop, Private, Marketplace, ...).
   */
  sellerType: SellerType;
  /**
   * Optional contact email.
   */
  email: string | null;
  /**
   * Optional contact phone number.
   */
  phone: string | null;
  /**
   * Optional website URL (if available).
   */
  websiteUrl: string | null;
  /**
   * Optional postal address structured as an `Address` domain value.
   *
   * When present this contains street, (extended) house number, city, region,
   * postal code and country as a single value object.
   */
  address: Address | null;
  /**
   * Creation timestamp (UTC).
   */
  createdAt: string;
  /**
   * Last update timestamp (UTC).
   */
  updatedAt: string;
};
/**
 * Strongly-typed identifier for a seller. Format: `trn:seller:{slug}`.
 */
export type SellerId = string;
/**
 * Represents the type/category of a seller.
 *
 * This enum is serialized/deserialized as screaming snake case (e.g. `SHOP`) and
 * persisted to the database as text. It is used across the sellers feature to
 * distinguish shops, private sellers, marketplaces and distributors.
 *
 * The type is intentionally strongly typed to avoid stringly-typed code and to
 * provide a small surface for formatting and parsing (via `strum` and `sqlx`).
 */
export type SellerType =
  /**
   * A retail shop or online store selling products directly to customers.
   */
  | 'SHOP'
  /**
   * A private (individual) seller — non-commercial person selling items.
   */
  | 'PRIVATE'
  /**
   * An online marketplace aggregating multiple sellers.
   */
  | 'MARKETPLACE'
  /**
   * A commercial distributor or wholesaler that supplies retailers.
   */
  | 'DISTRIBUTOR';
/**
 * Represents the service class(es) for a rolling stock or service.
 *
 * | **Variant**                      | **Description**           |
 * |:---------------------------------|:--------------------------|
 * | `ServiceLevel::First`            | `1st class`               |
 * | `ServiceLevel::Second`           | `2nd class`               |
 * | `ServiceLevel::Third`            | `3rd class`               |
 * | `ServiceLevel::FirstSecond`      | `Mixed 1st/2nd class`     |
 * | `ServiceLevel::SecondThird`      | `Mixed 2nd/3rd class`     |
 * | `ServiceLevel::FirstSecondThird` | `Mixed 1st/2nd/3rd class` |
 *
 * Parsing: `TryFrom<&str>` is implemented and accepts the string forms above
 * (whitespace is trimmed). Formatting: `Display` is implemented and produces
 * the corresponding string representation.
 */
export type ServiceLevel =
  | 'FIRST'
  | 'SECOND'
  | 'THIRD'
  | 'FIRST_SECOND'
  | 'SECOND_THIRD'
  | 'FIRST_SECOND_THIRD';
export type SettingsDto = {
  id: bigint;
  currency: Currency;
  lengthUnit: MeasureUnit;
  favoriteScale: Scale;
  favoritePowerMethod: PowerMethod;
  languageCode: string;
};
/**
 * Details for an item that was sold.
 *
 * We keep both the original purchase information and the sale data so the
 * application can show provenance (what was paid originally) together with
 * the sale outcome. The item should be excluded from collection value
 * aggregations once sold.
 */
export type SoldInfo = {
  /**
   * Unique identifier for the original purchase record (or the sale record,
   * depending on how you model identifiers). This is the canonical id for
   * the persisted purchase_info row.
   */
  id: PurchaseInfoId;
  /**
   * Date when the item was originally purchased (ISO `YYYY-MM-DD`).
   */
  purchase_date: string;
  /**
   * Original purchase price, if available.
   *
   * Use `None` to indicate the original price is unknown or not stored.
   */
  purchase_price: MonetaryAmount | null;
  /**
   * Date when the item was sold (ISO `YYYY-MM-DD`).
   */
  sale_date: string;
  /**
   * Price obtained when the item was sold. This value is required for
   * `Sold` records because a sale without a price is not meaningful for
   * financial reporting.
   */
  sale_price: MonetaryAmount;
  /**
   * Optional buyer identifier (when the buyer is a tracked entity).
   */
  buyer: string | null;
  /**
   * Optional seller identifier for completeness (may be the shop that
   * originally sold the item or the intermediary that handled the sale).
   */
  seller: string | null;
};
/**
 * The technical specification data for a rolling stock model
 */
export type TechnicalSpecifications = {
  /**
   * the minimum drivable radius
   */
  minimum_radius: Radius | null;
  /**
   * the coupling
   */
  coupling: Coupling | null;
  /**
   * has a flywheel fitted
   */
  flywheel_fitted: FeatureFlag | null;
  /**
   * body shell type
   */
  body_shell: BodyShellType | null;
  /**
   * chassis type
   */
  chassis: ChassisType | null;
  /**
   * has interior lighting
   */
  interior_lights: FeatureFlag | null;
  /**
   * has lights
   */
  lights: FeatureFlag | null;
  /**
   * has sprung buffers
   */
  sprung_buffers: FeatureFlag | null;
};
export type TechnicalSpecificationsInput = {
  minimum_radius: number | null;
  coupling: CouplingInput | null;
  flywheel_fitted: string | null;
  body_shell: string | null;
  chassis: string | null;
  interior_lights: string | null;
  lights: string | null;
  sprung_buffers: string | null;
};
/**
 * Payload for updating a collection item.
 */
export type UpdateCollectionItemInput = {
  id: string;
  brand: string;
  catalogNumber: string;
  title: string;
  scale: string;
  powerSystem: string;
  description: string | null;
  tags: string[];
};
export type UpdateSellerPayload = {
  id: string;
  name: string;
  sellerType: SellerType;
  email: string | null;
  phone: string | null;
  websiteUrl: string | null;
  streetAddress: string | null;
  extendedAddress: string | null;
  city: string | null;
  stateRegion: string | null;
  postalCode: string | null;
  countryCode: string | null;
  createdAt: string | null;
};
export type UpdateSettingsPayload = {
  currency: Currency;
  lengthUnit: MeasureUnit;
  favoriteScale: Scale;
  favoritePowerMethod: PowerMethod;
  languageCode: string;
};
/**
 * Domain model representing a user's wishlist.
 *
 * A `Wishlist` is a named collection of `WishlistItem`s. It carries
 * optional notes, a flag indicating whether it is the default list, and
 * a stable identifier used across the application. Business logic should
 * operate on this aggregate root when mutating the contained items.
 */
export type Wishlist = {
  /**
   * Unique identifier for the wishlist.
   */
  id: WishlistId;
  /**
   * Human-readable name for the wishlist.
   */
  name: string;
  /**
   * Optional free-form notes attached to the wishlist.
   */
  notes: string | null;
  /**
   * Whether this wishlist is the default for the user.
   */
  is_default: boolean;
  /**
   * Items contained in this wishlist.
   */
  items: WishlistItem[];
};
/**
 * Strongly-typed identifier for a wishlist.
 *
 * Wraps a formatted `String` of the form `trn:wishlist:{uuid}`.
 */
export type WishlistId = string;
/**
 * A single item within a `Wishlist`.
 *
 * `WishlistItem` models the user-facing properties of an item the user
 * wants to track or acquire. It intentionally does not carry a reference
 * to its parent `Wishlist` as it is used as a value object inside the
 * aggregate. Business operations that need the wishlist context should
 * operate on the `Wishlist` aggregate.
 */
export type WishlistItem = {
  /**
   * Stable identifier for this wishlist item.
   */
  id: WishlistItemId;
  /**
   * Identifier of the referenced railway model.
   */
  railway_model_id: RailwayModelId;
  /**
   * The user's priority for this item.
   */
  priority: WishlistPriority;
  /**
   * The current procurement/status lifecycle state for the item.
   */
  status: WishlistStatus;
  /**
   * Date the item was added to the wishlist (YYYY-MM-DD).
   */
  added_date: string;
  /**
   * Optional date when the item was removed from the wishlist.
   */
  removed_date: string | null;
  /**
   * Optional free-form notes attached to the item.
   */
  notes: string | null;
  /**
   * Desired price the user is willing to pay for the item (in cents).
   */
  desired_price: MonetaryAmount | null;
  /**
   * Actual purchased price if available (in cents).
   */
  purchased_price: MonetaryAmount | null;
};
/**
 * Strongly-typed identifier for a wishlist item.
 *
 * Wraps a formatted `String` of the form `trn:wishlist-item:{uuid}`.
 */
export type WishlistItemId = string;
/**
 * Lightweight preview information for a wishlist.
 *
 * Primarily used for list views where a full wishlist and its items are
 * not required. `total_value` maps a `Currency` to the summed amount
 * (stored in the DB as integer amounts, typically the smallest unit, e.g.
 * cents) for the wishlist items in that currency.
 */
export type WishlistPreview = {
  id: WishlistId;
  name: string;
  notes: string | null;
  is_default: boolean;
  count: bigint;
  updated_at: string;
  total_value: Partial<{ [key in Currency]: bigint }>;
};
/**
 * Priority assigned to a wishlist item.
 *
 * Indicates how important or urgent an item is for the user. The enum is
 * serialized as SCREAMING_SNAKE_CASE (e.g. `"LOW"`, `"NORMAL"`, `"HIGH"`)
 * and supports case-insensitive parsing via `FromStr` thanks to
 * `strum_macros::EnumString`.
 *
 * The default variant is `Normal`.
 */
export type WishlistPriority = 'LOW' | 'NORMAL' | 'HIGH';
/**
 * Status of a wishlist item.
 *
 * Represents the current lifecycle state for an item on the wishlist. The
 * enum is serialized as SCREAMING_SNAKE_CASE (e.g. `"WANTED"`,
 * `"ON_ORDER"`, `"PURCHASED"`, `"IGNORED"`) and supports case-insensitive
 * parsing via `FromStr` through `strum_macros::EnumString`.
 *
 * The default variant is `Wanted`.
 */
export type WishlistStatus = 'WANTED' | 'ON_ORDER' | 'PURCHASED' | 'IGNORED';

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE, Channel as TAURI_CHANNEL } from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
  listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg)
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          }
        });
      }
    }
  );
}
