use std::collections::HashMap;

/// Maps external IDs from imported data to internal database IDs.
///
/// After records are inserted into the database, this service tracks the mapping
/// between the external IDs in the manifest and the internal UUIDs generated by the application.
pub struct IdMapperService {
    /// Maps external manufacturer IDs to internal IDs
    manufacturer_map: HashMap<String, String>,
    /// Maps external railway company IDs to internal IDs
    railway_company_map: HashMap<String, String>,
    /// Maps external railway model IDs to internal IDs
    railway_model_map: HashMap<String, String>,
    /// Maps external seller IDs to internal IDs
    seller_map: HashMap<String, String>,
}

impl IdMapperService {
    /// Create a new ID mapper service.
    pub fn new() -> Self {
        Self {
            manufacturer_map: HashMap::new(),
            railway_company_map: HashMap::new(),
            railway_model_map: HashMap::new(),
            seller_map: HashMap::new(),
        }
    }

    /// Register a manufacturer ID mapping.
    pub fn map_manufacturer(&mut self, external_id: String, internal_id: String) {
        self.manufacturer_map.insert(external_id, internal_id);
    }

    /// Register a railway company ID mapping.
    pub fn map_railway_company(&mut self, external_id: String, internal_id: String) {
        self.railway_company_map.insert(external_id, internal_id);
    }

    /// Register a railway model ID mapping.
    pub fn map_railway_model(&mut self, external_id: String, internal_id: String) {
        self.railway_model_map.insert(external_id, internal_id);
    }

    /// Register a seller ID mapping.
    pub fn map_seller(&mut self, external_id: String, internal_id: String) {
        self.seller_map.insert(external_id, internal_id);
    }

    /// Resolve a manufacturer ID (external to internal).
    pub fn resolve_manufacturer(&self, external_id: &str) -> Option<&str> {
        self.manufacturer_map.get(external_id).map(|s| s.as_str())
    }

    /// Resolve a railway company ID (external to internal).
    pub fn resolve_railway_company(&self, external_id: &str) -> Option<&str> {
        self.railway_company_map
            .get(external_id)
            .map(|s| s.as_str())
    }

    /// Resolve a railway model ID (external to internal).
    pub fn resolve_railway_model(&self, external_id: &str) -> Option<&str> {
        self.railway_model_map.get(external_id).map(|s| s.as_str())
    }

    /// Resolve a seller ID (external to internal).
    pub fn resolve_seller(&self, external_id: &str) -> Option<&str> {
        self.seller_map.get(external_id).map(|s| s.as_str())
    }
}

impl Default for IdMapperService {
    fn default() -> Self {
        Self::new()
    }
}
