pub(crate) mod box_condition;
mod collection;
mod collection_events;
mod collection_id;
mod collection_item;
mod collection_item_id;
mod collection_item_update;
mod collection_item_view;
mod collection_params;
mod collection_railway_model;
mod collection_summary;
mod collection_view;
mod depot_view;
mod digital_setup;
pub(crate) mod model_condition;
mod new_collection_item;
mod owned_rolling_stock;
mod owned_rolling_stock_id;
mod owned_rolling_stock_view;
pub(crate) mod purchase_condition;
mod purchase_info;
mod purchase_info_id;
mod repository;

pub use box_condition::BoxCondition;
pub use collection::Collection;
pub use collection_events::CollectionEvent;
pub use collection_id::CollectionId;
pub use collection_item::CollectionItem;
pub use collection_item_id::CollectionItemId;
pub use collection_item_update::CollectionItemUpdate;
pub use collection_item_update::UpdateCollectionItemInput;
pub use collection_item_view::CollectionItemView;
pub use collection_params::NewCollectionItemParams;
pub use collection_railway_model::CollectionRailwayModel;
pub use collection_summary::CollectionSummary;
pub use collection_view::CollectionView;
pub use depot_view::DepotRollingStockView;
pub use depot_view::DepotView;
pub use digital_setup::DigitalSetup;
pub use model_condition::ModelCondition;
pub use new_collection_item::NewCollectionItem;
pub use owned_rolling_stock::OwnedRollingStock;
pub use owned_rolling_stock_id::OwnedRollingStockId;
pub use owned_rolling_stock_view::OwnedRollingStockView;
pub use purchase_condition::PurchaseCondition;
pub use purchase_info::PurchaseInfo;
pub use purchase_info::{PreOrderInfo, PurchasedInfo, SoldInfo};
pub use purchase_info_id::PurchaseInfoId;
pub use repository::CollectionRepository;
pub use repository::CollectionUowExt;

#[cfg(test)]
pub use repository::MockCollectionRepository;
