/**
 * Centralized Tauri IPC adapter.
 *
 * This module provides a standardized way to invoke Tauri commands with
 * consistent error handling and normalization. All services should use
 * `safeInvoke` instead of directly calling the Tauri `invoke` API.
 */

import { invoke } from '@tauri-apps/api/core';
import type { NormalizedError, SafeResult } from '../domain/errors';

/**
 * Rust CommandError as serialized by Tauri.
 * This matches the TypeScript type generated by tauri-specta.
 */
type CommandError =
  | { DatabaseError: string }
  | { NotFound: string }
  | { ValidationError: Record<string, unknown> }
  | { PermissionDenied: string }
  | { Unknown: string | { message?: string; error_id?: string } }
  | { BusinessRule: string }
  | { Conflict: string };

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function normalizeValidationIssue(value: unknown): string {
  if (typeof value === 'string') {
    return value;
  }

  if (isRecord(value)) {
    if (typeof value.message === 'string' && value.message.length > 0) {
      return value.message;
    }

    if (typeof value.code === 'string' && value.code.length > 0) {
      return value.code;
    }
  }

  return 'Invalid value';
}

function normalizeValidationFields(value: unknown): Record<string, string> {
  if (!isRecord(value)) {
    return { _general: 'Invalid input' };
  }

  return Object.fromEntries(
    Object.entries(value).map(([field, rawIssue]) => {
      if (Array.isArray(rawIssue)) {
        const messages = rawIssue
          .map((issue) => normalizeValidationIssue(issue))
          .filter((msg) => msg.length > 0);

        return [field, messages.length > 0 ? messages.join('; ') : 'Invalid value'];
      }

      return [field, normalizeValidationIssue(rawIssue)];
    })
  );
}

/**
 * Normalize a Rust CommandError into our application's NormalizedError format.
 *
 * @param error - The error from Rust (CommandError) or a JavaScript Error
 * @returns A normalized error object
 */
function normalizeError(error: unknown): NormalizedError {
  // Handle Rust CommandError (tagged union)
  if (error && typeof error === 'object') {
    const err = error as Partial<CommandError>;

    if ('DatabaseError' in err && typeof err.DatabaseError === 'string') {
      return {
        kind: 'database',
        message: err.DatabaseError,
        retryable: true
      };
    }

    if ('NotFound' in err && typeof err.NotFound === 'string') {
      return {
        kind: 'not_found',
        message: err.NotFound,
        retryable: false
      };
    }

    if ('ValidationError' in err && typeof err.ValidationError === 'object') {
      return {
        kind: 'validation',
        message: 'Validation failed',
        fields: normalizeValidationFields(err.ValidationError),
        retryable: false
      };
    }

    if ('PermissionDenied' in err && typeof err.PermissionDenied === 'string') {
      return {
        kind: 'permission_denied',
        message: err.PermissionDenied,
        retryable: false
      };
    }

    if ('Unknown' in err) {
      if (typeof err.Unknown === 'string') {
        return {
          kind: 'unknown',
          message: err.Unknown,
          retryable: false
        };
      }

      if (isRecord(err.Unknown)) {
        return {
          kind: 'unknown',
          message:
            typeof err.Unknown.message === 'string' && err.Unknown.message.length > 0
              ? err.Unknown.message
              : 'An unexpected error occurred',
          ...(typeof err.Unknown.error_id === 'string' ? { errorId: err.Unknown.error_id } : {}),
          retryable: false
        };
      }
    }

    if ('BusinessRule' in err && typeof err.BusinessRule === 'string') {
      return {
        kind: 'unknown',
        message: err.BusinessRule,
        retryable: false
      };
    }

    if ('Conflict' in err && typeof err.Conflict === 'string') {
      return {
        kind: 'unknown',
        message: err.Conflict,
        retryable: false
      };
    }
  }

  // Handle JavaScript Error objects
  if (error instanceof Error) {
    return {
      kind: 'unknown',
      message: error.message || 'An unexpected error occurred',
      retryable: false
    };
  }

  // Fallback for completely unknown error types
  return {
    kind: 'unknown',
    message: String(error) || 'An unexpected error occurred',
    retryable: false
  };
}

/**
 * Safely invoke a Tauri command with normalized error handling.
 *
 * This function wraps the raw Tauri `invoke` API and provides:
 * - Consistent error shape across all commands
 * - Automatic error normalization from Rust CommandError
 * - Type-safe return values
 *
 * @template T - The expected return type from the command
 * @param command - The name of the Tauri command to invoke
 * @param args - Arguments to pass to the command
 * @returns A SafeResult containing either the data or a normalized error
 *
 * @example
 * ```typescript
 * const result = await safeInvoke<Wishlist>('get_wishlist_by_id', { id: '123' });
 * if (result.ok) {
 *   console.log('Wishlist:', result.data);
 * } else {
 *   console.error('Error:', result.error.message);
 *   if (isValidationError(result.error)) {
 *     // Handle field-specific validation errors
 *     Object.entries(result.error.fields).forEach(([field, msg]) => {
 *       console.error(`  ${field}: ${msg}`);
 *     });
 *   }
 * }
 * ```
 */
export async function safeInvoke<T>(
  command: string,
  args?: Record<string, unknown>
): Promise<SafeResult<T>> {
  try {
    const data = await invoke<T>(command, args ?? {});
    return { ok: true, data };
  } catch (error) {
    return { ok: false, error: normalizeError(error) };
  }
}

/**
 * Invoke a Tauri command and throw a normalized error on failure.
 *
 * This is useful when you want to use try/catch instead of checking result.ok.
 *
 * @template T - The expected return type from the command
 * @param command - The name of the Tauri command to invoke
 * @param args - Arguments to pass to the command
 * @returns The command result
 * @throws {NormalizedError} If the command fails
 *
 * @example
 * ```typescript
 * try {
 *   const wishlist = await invokeOrThrow<Wishlist>('get_wishlist_by_id', { id: '123' });
 *   console.log('Wishlist:', wishlist);
 * } catch (error) {
 *   if (isNotFoundError(error as NormalizedError)) {
 *     // Handle not found
 *   }
 * }
 * ```
 */
export async function invokeOrThrow<T>(
  command: string,
  args?: Record<string, unknown>
): Promise<T> {
  const result = await safeInvoke<T>(command, args);
  if (!result.ok) {
    throw result.error;
  }
  return result.data;
}

/**
 * Retry a Tauri command invocation with exponential backoff.
 *
 * @template T - The expected return type from the command
 * @param command - The name of the Tauri command to invoke
 * @param args - Arguments to pass to the command
 * @param maxRetries - Maximum number of retry attempts (default: 3)
 * @param initialDelay - Initial delay in milliseconds (default: 100)
 * @returns A SafeResult containing either the data or a normalized error
 */
export async function safeInvokeWithRetry<T>(
  command: string,
  args?: Record<string, unknown>,
  maxRetries = 3,
  initialDelay = 100
): Promise<SafeResult<T>> {
  let lastError: NormalizedError | null = null;
  let delay = initialDelay;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    const result = await safeInvoke<T>(command, args);

    if (result.ok) {
      return result;
    }

    lastError = result.error;

    // Don't retry if error is not retryable
    if (!result.error.retryable) {
      return result;
    }

    // Don't sleep after last attempt
    if (attempt < maxRetries) {
      await new Promise((resolve) => setTimeout(resolve, delay));
      delay *= 2; // Exponential backoff
    }
  }

  // Return the last error
  return { ok: false, error: lastError! };
}

/**
 * Wrap a typed `commands.*` call (which returns a `typedError` result) into a
 * `SafeResult`, normalizing the backend error into a `NormalizedError`.
 *
 * This bridges the tauri-specta `{ status: "ok" | "error" }` shape that
 * `commands.*` functions return into the application-wide `SafeResult` shape,
 * so callers can keep using `if (result.ok)` checks and `getErrorMessage`
 * without any further changes.
 *
 * @example
 * ```typescript
 * import { commands } from '$lib/bindings';
 * import { safeCommand } from '$lib/shared/services/TauriAdapter';
 *
 * const result = await safeCommand(commands.getWishlists());
 * if (result.ok) {
 *   console.log(result.data);
 * }
 * ```
 */
export async function safeCommand<T, E>(
  promise: Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }>
): Promise<SafeResult<T>> {
  const result = await promise;
  if (result.status === 'ok') {
    return { ok: true, data: result.data };
  }
  return { ok: false, error: normalizeError(result.error) };
}
