/**
 * Common Zod schemas shared across multiple form schemas.
 *
 * All values mirror the types generated by tauri-specta in bindings.ts.
 * Update these when the Rust types change and `pnpm specta:generate` is re-run.
 */

import { z } from 'zod';

/** Currency — bindings.ts `Currency` */
export const currencySchema = z.enum(['EUR', 'USD', 'GBP', 'JPY']);

/** Application language — bindings.ts `Language` */
export const languageSchema = z.enum(['en', 'it']);

/** Measurement unit — bindings.ts `MeasureUnit` */
export const measureUnitSchema = z.enum(['Metric', 'Imperial']);

/** Application theme — bindings.ts `AppTheme` */
export const appThemeSchema = z.enum(['steampunk-light', 'steampunk-dark', 'system']);

/** Wishlist item priority — bindings.ts `WishlistPriority` */
export const wishlistPrioritySchema = z.enum(['LOW', 'NORMAL', 'HIGH']);

/** Purchase condition — bindings.ts `PurchaseCondition` */
export const purchaseConditionSchema = z.enum(['NEW', 'PRE_OWNED']);

/** Physical model condition — bindings.ts `ModelCondition` */
export const modelConditionSchema = z.enum([
  'MINT',
  'NEAR_MINT',
  'EXCELLENT',
  'VERY_GOOD',
  'GOOD',
  'FAIR',
  'POOR',
  'FOR_PARTS'
]);

/** Packaging condition — bindings.ts `BoxCondition` */
export const boxConditionSchema = z.enum([
  'ORIGINAL_MINT',
  'ORIGINAL_GOOD',
  'ORIGINAL_WORN',
  'REPLACEMENT_BOX',
  'NO_BOX'
]);

/** Seller type — bindings.ts `SellerType` */
export const sellerTypeSchema = z.enum([
  'SHOP',
  'PRIVATE',
  'MANUFACTURER',
  'MARKETPLACE',
  'DISTRIBUTOR'
]);
