/**
 * Theme Settings API Contract
 *
 * This file defines the TypeScript types for theme-related settings
 * that will be generated by specta from Rust types.
 *
 * Feature: 011-steampunk-theme
 * Created: 2026-01-30
 */

// ============================================================================
// Enums
// ============================================================================

/**
 * User's theme preference choice.
 * Stored in SQLite settings table.
 */
export type ThemeValue = 'steampunk-light' | 'steampunk-dark' | 'system';

/**
 * The actual theme applied after resolving system preference.
 * Used for CSS class application.
 */
export type ResolvedTheme = 'light' | 'dark';

// ============================================================================
// DTOs (Data Transfer Objects)
// ============================================================================

/**
 * Extended SettingsDto with theme field.
 * Returned by get_settings command.
 */
export interface SettingsDto {
  id: number;
  currency: Currency;
  lengthUnit: MeasureUnit;
  favoriteScale: Scale;
  favoritePowerMethod: PowerMethod;
  languageCode: string;
  /** NEW: User's theme preference */
  theme: ThemeValue;
}

/**
 * Extended UpdateSettingsPayload with theme field.
 * Sent to update_settings command.
 */
export interface UpdateSettingsPayload {
  currency: Currency;
  lengthUnit: MeasureUnit;
  favoriteScale: Scale;
  favoritePowerMethod: PowerMethod;
  languageCode: string;
  /** NEW: User's theme preference */
  theme: ThemeValue;
}

// ============================================================================
// Store State
// ============================================================================

/**
 * Frontend theme store state.
 * Managed by themeStore.svelte.ts
 */
export interface ThemeState {
  /** User's stored preference from settings */
  current: ThemeValue;
  /** Actual theme after system preference resolution */
  resolved: ResolvedTheme;
  /** True during initial settings load */
  isLoading: boolean;
}

// ============================================================================
// Tauri Command Signatures
// ============================================================================

/**
 * get_settings - Retrieve current user settings including theme
 *
 * @returns Promise<Result<SettingsDto, CommandError>>
 *
 * Example usage:
 * ```typescript
 * const result = await commands.getSettings();
 * if (result.status === 'ok') {
 *   themeStore.setTheme(result.data.theme);
 * }
 * ```
 */

/**
 * update_settings - Update user settings including theme
 *
 * @param payload - UpdateSettingsPayload with all settings fields
 * @returns Promise<Result<SettingsDto, CommandError>>
 *
 * Example usage:
 * ```typescript
 * const result = await commands.updateSettings({
 *   ...currentSettings,
 *   theme: 'steampunk-dark'
 * });
 * ```
 */

// ============================================================================
// CSS Custom Properties Contract
// ============================================================================

/**
 * Theme Token Categories
 *
 * These CSS custom properties will be defined in theme CSS files
 * and consumed by Tailwind utilities and Skeleton components.
 */

export interface ThemeTokens {
  // Surface scale (backgrounds, cards, borders)
  surface: {
    50: string; // Brightest
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
    950: string; // Darkest
  };

  // Primary (brass in light, copper in dark)
  primary: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string; // Core color
    600: string;
    700: string;
    800: string;
    900: string;
    950: string;
  };

  // Secondary (leather in light, mahogany in dark)
  secondary: typeof this.primary;

  // Tertiary (verdigris in light, oxidized bronze in dark)
  tertiary: typeof this.primary;

  // Accent (steam blue in light, furnace orange in dark)
  accent: typeof this.primary;

  // Semantic colors
  error: { 50: string; 500: string; 900: string };
  success: { 50: string; 500: string; 900: string };
  warning: { 50: string; 500: string; 900: string };

  // Typography
  fontFamily: {
    heading: string;
    body: string;
    accent: string;
  };
}

// ============================================================================
// Component Props Contracts
// ============================================================================

/**
 * RivetedCard component props
 */
export interface RivetedCardProps {
  /** Visual style variant */
  variant?: 'panel' | 'plate' | 'frame';
  /** Rivet placement */
  rivets?: 'corners' | 'edges' | 'none';
  /** Internal padding */
  padding?: 'none' | 'sm' | 'md' | 'lg';
  /** Additional CSS classes */
  class?: string;
}

/**
 * ToggleValve component props
 */
export interface ToggleValveProps {
  /** Bindable toggle state */
  checked?: boolean;
  /** Disabled state */
  disabled?: boolean;
  /** Valve size */
  size?: 'sm' | 'md' | 'lg';
  /** Accessibility label */
  label?: string;
}

/**
 * PressureGauge component props
 */
export interface PressureGaugeProps {
  /** Current value (0-100) */
  value?: number;
  /** Maximum value */
  max?: number;
  /** Gauge label */
  label?: string;
  /** Display unit */
  unit?: string;
  /** Danger threshold (default 80) */
  danger?: number;
}

/**
 * RailDivider component props
 */
export interface RailDividerProps {
  /** Track type */
  variant?: 'single' | 'double';
  /** Additional CSS classes */
  class?: string;
}

// ============================================================================
// Type Re-exports (from existing bindings.ts)
// ============================================================================

// These types already exist and will be imported from bindings.ts
// Listed here for contract completeness

export type Currency = string; // Actual enum in bindings.ts
export type MeasureUnit = string; // Actual enum in bindings.ts
export type Scale = string; // Actual enum in bindings.ts
export type PowerMethod = string; // Actual enum in bindings.ts
