pub(crate) mod availability_status;
pub(crate) mod body_shell_type;
pub(crate) mod category;
pub(crate) mod chassis_type;
pub(crate) mod control;
mod coupling;
pub(crate) mod coupling_socket;
mod dcc_interface;
mod delivery_date;
pub(crate) mod epoch;
pub(crate) mod feature_flag;
mod length_over_buffers;
pub mod localized_field;
pub(crate) mod power_method;
mod product_code;
mod radius;
#[allow(clippy::module_inception)]
mod railway_model;
mod railway_model_event;
mod railway_model_id;
mod railway_model_params;
pub mod railway_model_translation;
mod railway_model_view;
mod repository;
mod rolling_stock;
mod rolling_stock_id;
mod rolling_stock_params;
mod service_level;
mod technical_specifications;

pub use availability_status::AvailabilityStatus;
pub use body_shell_type::BodyShellType;
pub use category::Category;
pub use category::ElectricMultipleUnitType;
pub use category::FreightCarType;
pub use category::LocomotiveType;
pub use category::PassengerCarType;
pub use category::RailcarType;
pub use category::RollingStockCategory;
pub use chassis_type::ChassisType;
pub use control::Control;
pub use coupling::Coupling;
pub use coupling_socket::CouplingSocket;
pub use dcc_interface::DccInterface;
pub use delivery_date::DeliveryDate;
pub use epoch::Epoch;
pub use epoch::EpochKind;
pub use feature_flag::FeatureFlag;
pub use length_over_buffers::LengthOverBuffers;
pub use localized_field::LocalizedField;
pub use power_method::PowerMethod;
pub use product_code::ProductCode;
pub use radius::{Radius, RadiusError};
pub use railway_model::RailwayModel;
pub use railway_model_event::RailwayModelEvent;
pub use railway_model_id::RailwayModelId;
pub use railway_model_id::validate_railway_model_id;
pub use railway_model_params::RailwayModelParams;
pub use railway_model_translation::{RailwayModelTranslationEntry, RailwayModelTranslations};
pub use railway_model_view::{
    RailwayModelManufacturer, RailwayModelView, RollingStockRailway, RollingStockView,
};
pub use repository::RailwayModelRepository;
pub use repository::RailwayModelUowExt;
pub use rolling_stock::RollingStock;
pub use rolling_stock::RollingStockDccPatch;
pub use rolling_stock::RollingStockSpecPatch;
pub use rolling_stock_id::RollingStockId;
pub use rolling_stock_params::RollingStockParams;
pub use service_level::ServiceLevel;
pub use technical_specifications::{TechnicalSpecifications, TechnicalSpecificationsBuilder};

#[cfg(test)]
pub use repository::MockRailwayModelRepository;
