// Calendar primitive types: Year and Month
//
// These newtypes wrap `i32` / `u8` with business-rule validation baked in.
// They are transparent to both serde (JSON remains a plain number) and specta
// (TypeScript binding remains `number`), so the API contract is unchanged.

use serde::{Deserialize, Serialize};
use thiserror::Error;

// ---------------------------------------------------------------------------
// Year
// ---------------------------------------------------------------------------

/// A valid calendar year in the range 2000–2100.
///
/// The inner value is serialized / deserialized as a plain JSON number.
/// TypeScript bindings generated by specta also emit `number`.
#[repr(transparent)]
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, specta::Type,
)]
#[serde(transparent)]
#[specta(transparent)]
pub struct Year(i32);

/// Error returned when constructing a [`Year`] with an out-of-range value.
#[derive(Debug, Error)]
#[error("year {0} is out of range; must be between 2000 and 2100")]
pub struct YearError(pub i32);

impl Year {
    /// The lower bound (inclusive) for valid years.
    pub const MIN: i32 = 1900;
    /// The upper bound (inclusive) for valid years.
    pub const MAX: i32 = 2100;

    /// Returns the inner primitive value.
    #[inline]
    pub const fn value(self) -> i32 {
        self.0
    }
}

impl TryFrom<i32> for Year {
    type Error = YearError;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        if (Self::MIN..=Self::MAX).contains(&value) {
            Ok(Self(value))
        } else {
            Err(YearError(value))
        }
    }
}

impl From<Year> for i32 {
    fn from(y: Year) -> Self {
        y.0
    }
}

impl garde::Validate for Year {
    type Context = ();

    fn validate_into(
        &self,
        _ctx: &Self::Context,
        parent: &mut dyn FnMut() -> garde::Path,
        report: &mut garde::Report,
    ) {
        if !(Self::MIN..=Self::MAX).contains(&self.0) {
            report.append(parent(), garde::Error::new("error_year_out_of_range"));
        }
    }
}

// ---------------------------------------------------------------------------
// Month
// ---------------------------------------------------------------------------

/// A valid calendar month in the range 1–12.
///
/// The inner value is serialized / deserialized as a plain JSON number.
/// TypeScript bindings generated by specta also emit `number`.
#[repr(transparent)]
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, specta::Type,
)]
#[serde(transparent)]
#[specta(transparent)]
pub struct Month(u8);

/// Error returned when constructing a [`Month`] with an out-of-range value.
#[derive(Debug, Error)]
#[error("month {0} is out of range; must be between 1 and 12")]
pub struct MonthError(pub u8);

impl Month {
    /// The lower bound (inclusive) for valid months.
    pub const MIN: u8 = 1;
    /// The upper bound (inclusive) for valid months.
    pub const MAX: u8 = 12;

    /// Returns the inner primitive value.
    #[inline]
    pub const fn value(self) -> u8 {
        self.0
    }

    /// Returns the English name of the month.
    pub const fn name(self) -> &'static str {
        match self.0 {
            1 => "January",
            2 => "February",
            3 => "March",
            4 => "April",
            5 => "May",
            6 => "June",
            7 => "July",
            8 => "August",
            9 => "September",
            10 => "October",
            11 => "November",
            12 => "December",
            _ => "Invalid",
        }
    }
}

impl TryFrom<u8> for Month {
    type Error = MonthError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        if (Self::MIN..=Self::MAX).contains(&value) {
            Ok(Self(value))
        } else {
            Err(MonthError(value))
        }
    }
}

impl From<Month> for u8 {
    fn from(m: Month) -> Self {
        m.0
    }
}

impl garde::Validate for Month {
    type Context = ();

    fn validate_into(
        &self,
        _ctx: &Self::Context,
        parent: &mut dyn FnMut() -> garde::Path,
        report: &mut garde::Report,
    ) {
        if !(Self::MIN..=Self::MAX).contains(&self.0) {
            report.append(parent(), garde::Error::new("error_month_out_of_range"));
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // --- Year ---

    #[test]
    fn year_accepts_lower_bound() {
        assert!(Year::try_from(1900).is_ok());
    }

    #[test]
    fn year_accepts_upper_bound() {
        assert!(Year::try_from(2100).is_ok());
    }

    #[test]
    fn year_accepts_mid_range() {
        let y = Year::try_from(2026).unwrap();
        assert_eq!(y.value(), 2026);
    }

    #[test]
    fn year_rejects_below_min() {
        let err = Year::try_from(1899).unwrap_err();
        assert_eq!(err.0, 1899);
    }

    #[test]
    fn year_rejects_above_max() {
        let err = Year::try_from(2101).unwrap_err();
        assert_eq!(err.0, 2101);
    }

    #[test]
    fn year_round_trips_serde() {
        let y = Year::try_from(2026).unwrap();
        let json = serde_json::to_string(&y).unwrap();
        assert_eq!(json, "2026");
        let restored: Year = serde_json::from_str(&json).unwrap();
        assert_eq!(restored, y);
    }

    // --- Month ---

    #[test]
    fn month_accepts_lower_bound() {
        assert!(Month::try_from(1).is_ok());
    }

    #[test]
    fn month_accepts_upper_bound() {
        assert!(Month::try_from(12).is_ok());
    }

    #[test]
    fn month_accepts_mid_range() {
        let m = Month::try_from(6).unwrap();
        assert_eq!(m.value(), 6);
        assert_eq!(m.name(), "June");
    }

    #[test]
    fn month_rejects_zero() {
        let err = Month::try_from(0).unwrap_err();
        assert_eq!(err.0, 0);
    }

    #[test]
    fn month_rejects_above_max() {
        let err = Month::try_from(13).unwrap_err();
        assert_eq!(err.0, 13);
    }

    #[test]
    fn month_round_trips_serde() {
        let m = Month::try_from(3).unwrap();
        let json = serde_json::to_string(&m).unwrap();
        assert_eq!(json, "3");
        let restored: Month = serde_json::from_str(&json).unwrap();
        assert_eq!(restored, m);
    }

    #[test]
    fn month_names_are_correct() {
        let names = [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
        ];
        for (i, expected) in names.iter().enumerate() {
            let m = Month::try_from((i + 1) as u8).unwrap();
            assert_eq!(m.name(), *expected);
        }
    }
}
